name: Rebuild Docker-MediaWiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - run: |
          curl \
            --fail \
            --request POST \
            --url https://api.github.com/repos/femiwiki/docker-mediawiki/dispatches \
            --header "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            --header 'content-type: application/json' \
            --data '{
              "event_type": "bump-extension",
              "client_payload": {
                "extension": "${{ github.event.repository.name }}",
                "version": "${{ github.sha }}",
                "commits_url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
              }
            }'
